//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Task", Namespace="http://tempuri.org/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ServiceReference1.TaskOfString))]
    public partial class Task : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskOfString", Namespace="http://tempuri.org/")]
    public partial class TaskOfString : ServiceReference1.Task
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.DisabledCallForwardingSoap")]
    public interface DisabledCallForwardingSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddForwardRule", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.AddForwardRuleResponse> AddForwardRuleAsync(ServiceReference1.AddForwardRuleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveForwardRule", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.RemoveForwardRuleResponse> RemoveForwardRuleAsync(ServiceReference1.RemoveForwardRuleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLogs", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.GetLogsResponse> GetLogsAsync(ServiceReference1.GetLogsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddForwardRuleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddForwardRule", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.AddForwardRuleRequestBody Body;
        
        public AddForwardRuleRequest()
        {
        }
        
        public AddForwardRuleRequest(ServiceReference1.AddForwardRuleRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddForwardRuleRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string phoneNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string did;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string countryCode;
        
        public AddForwardRuleRequestBody()
        {
        }
        
        public AddForwardRuleRequestBody(string phoneNumber, string did, string countryCode)
        {
            this.phoneNumber = phoneNumber;
            this.did = did;
            this.countryCode = countryCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddForwardRuleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddForwardRuleResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.AddForwardRuleResponseBody Body;
        
        public AddForwardRuleResponse()
        {
        }
        
        public AddForwardRuleResponse(ServiceReference1.AddForwardRuleResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddForwardRuleResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.TaskOfString AddForwardRuleResult;
        
        public AddForwardRuleResponseBody()
        {
        }
        
        public AddForwardRuleResponseBody(ServiceReference1.TaskOfString AddForwardRuleResult)
        {
            this.AddForwardRuleResult = AddForwardRuleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveForwardRuleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveForwardRule", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.RemoveForwardRuleRequestBody Body;
        
        public RemoveForwardRuleRequest()
        {
        }
        
        public RemoveForwardRuleRequest(ServiceReference1.RemoveForwardRuleRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveForwardRuleRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string did;
        
        public RemoveForwardRuleRequestBody()
        {
        }
        
        public RemoveForwardRuleRequestBody(string did)
        {
            this.did = did;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveForwardRuleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveForwardRuleResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.RemoveForwardRuleResponseBody Body;
        
        public RemoveForwardRuleResponse()
        {
        }
        
        public RemoveForwardRuleResponse(ServiceReference1.RemoveForwardRuleResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveForwardRuleResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.TaskOfString RemoveForwardRuleResult;
        
        public RemoveForwardRuleResponseBody()
        {
        }
        
        public RemoveForwardRuleResponseBody(ServiceReference1.TaskOfString RemoveForwardRuleResult)
        {
            this.RemoveForwardRuleResult = RemoveForwardRuleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLogsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLogs", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetLogsRequestBody Body;
        
        public GetLogsRequest()
        {
        }
        
        public GetLogsRequest(ServiceReference1.GetLogsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLogsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int option;
        
        public GetLogsRequestBody()
        {
        }
        
        public GetLogsRequestBody(int option)
        {
            this.option = option;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLogsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLogsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.GetLogsResponseBody Body;
        
        public GetLogsResponse()
        {
        }
        
        public GetLogsResponse(ServiceReference1.GetLogsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLogsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.TaskOfString GetLogsResult;
        
        public GetLogsResponseBody()
        {
        }
        
        public GetLogsResponseBody(ServiceReference1.TaskOfString GetLogsResult)
        {
            this.GetLogsResult = GetLogsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface DisabledCallForwardingSoapChannel : ServiceReference1.DisabledCallForwardingSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class DisabledCallForwardingSoapClient : System.ServiceModel.ClientBase<ServiceReference1.DisabledCallForwardingSoap>, ServiceReference1.DisabledCallForwardingSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DisabledCallForwardingSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(DisabledCallForwardingSoapClient.GetBindingForEndpoint(endpointConfiguration), DisabledCallForwardingSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DisabledCallForwardingSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DisabledCallForwardingSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DisabledCallForwardingSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DisabledCallForwardingSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DisabledCallForwardingSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.AddForwardRuleResponse> ServiceReference1.DisabledCallForwardingSoap.AddForwardRuleAsync(ServiceReference1.AddForwardRuleRequest request)
        {
            return base.Channel.AddForwardRuleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.AddForwardRuleResponse> AddForwardRuleAsync(string phoneNumber, string did, string countryCode)
        {
            ServiceReference1.AddForwardRuleRequest inValue = new ServiceReference1.AddForwardRuleRequest();
            inValue.Body = new ServiceReference1.AddForwardRuleRequestBody();
            inValue.Body.phoneNumber = phoneNumber;
            inValue.Body.did = did;
            inValue.Body.countryCode = countryCode;
            return ((ServiceReference1.DisabledCallForwardingSoap)(this)).AddForwardRuleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.RemoveForwardRuleResponse> ServiceReference1.DisabledCallForwardingSoap.RemoveForwardRuleAsync(ServiceReference1.RemoveForwardRuleRequest request)
        {
            return base.Channel.RemoveForwardRuleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.RemoveForwardRuleResponse> RemoveForwardRuleAsync(string did)
        {
            ServiceReference1.RemoveForwardRuleRequest inValue = new ServiceReference1.RemoveForwardRuleRequest();
            inValue.Body = new ServiceReference1.RemoveForwardRuleRequestBody();
            inValue.Body.did = did;
            return ((ServiceReference1.DisabledCallForwardingSoap)(this)).RemoveForwardRuleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.GetLogsResponse> ServiceReference1.DisabledCallForwardingSoap.GetLogsAsync(ServiceReference1.GetLogsRequest request)
        {
            return base.Channel.GetLogsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetLogsResponse> GetLogsAsync(int option)
        {
            ServiceReference1.GetLogsRequest inValue = new ServiceReference1.GetLogsRequest();
            inValue.Body = new ServiceReference1.GetLogsRequestBody();
            inValue.Body.option = option;
            return ((ServiceReference1.DisabledCallForwardingSoap)(this)).GetLogsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DisabledCallForwardingSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.DisabledCallForwardingSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DisabledCallForwardingSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://didww-api.talknsave.net/CallForwarding.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.DisabledCallForwardingSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://didww-api.talknsave.net/CallForwarding.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            DisabledCallForwardingSoap,
            
            DisabledCallForwardingSoap12,
        }
    }
}
